name: Build GetStarted example
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: vcpkg
        run: |
          pwd
          mkdir .vcpkg
          touch .vcpkg/vcpkg.path.txt
          ls -al
          vcpkg integrate install
          vcpkg activate
      - name: csolution
        run: |
          csolution list packs -m -s GetStarted.csolution.yml > packs.txt
          test ! -s packs.txt || cpackget add -f packs.txt
          csolution convert -s GetStarted.csolution.yml -c GetStarted.Debug+AVH
          cbuild -v build/GetStarted/GCC/Debug+AVH/GetStarted.Debug+AVH.cprj
